name: check

on:
  pull_request:

jobs:
  error-check:
    name: Check errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.3.3
        with:
          jvm: temurin:1.17
          apps: ""

      - name: Check all errors
        run: make check
