name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 9 * * *

jobs:
  build:
    name: Format check and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: temurin:1.17
          apps: ""

      - name: Check errors
        run: ./run.sh check
