name: generate

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 9 * * *

jobs:
  error-check:
    name: Check errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: temurin:1.17
          apps: ""

      - name: Check all errors
        run: make check

      - name: Regenerate index
        run: make build

      - uses: stefanzweifel/git-auto-commit-action@v4.14.0
        with:
          file_pattern: README.md
          commit_message: "chore: auto update error index"
          commit_author: Github Actions <actions@github.com>
